### ISSUE TITLE
Github Actions to Build & Release APK

### ISSUE THREAD

**Issue by rexdivakar** [subeg7/flutter-mini-facebook-ui#1]
Hey Buddy, Im having issues using your github actions, can u please help me out !!

Let me know how we can connect further ?

**Comment by subeg7** [comment]
Hey  rexdivakar, sure. I will be more than happy to help.

My connections : 
 
LinkedIn : 
https://www.linkedin.com/in/subeg-aryal-a53818136

twitter : 
https://twitter.com/sbgarl



> Hey Buddy, Im having issues using your github actions, can u please help me out !!
> 
> Let me know how we can connect further ?
